[package]
name = "easymq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-lite = "^1.11.0"
lapin = { version = "^2.2.0", optional = true }
thiserror = "^1.0.20"
async-trait = "^0.1.59"
async-stream = "^0.3.2"

[features]
default = ["lapin"]
lapin = ["dep:lapin"]
