[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.4.0"
futures-lite = "1.13.0"
lapin = "2.1.1"
postcard = { version = "1.0.4", features = ["alloc"] }
serde = "1.0.162"
tokio = { version = "1.28.0", features = ["sync"] }
uuid = { version = "1.3.2", features = ["v4"] }
