[package]
name = "simple_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "^5.1.0"
futures-lite = "^1.11.0"
lapin = "^2.2.0"
postcard = { version = "^1.0.1", features = ["alloc"] }
serde = "^1.0.94"
tokio = { version = "^1.22.0", no-default-features = true, features = ["sync"] }
uuid = { version = "^1.3.2", features = ["v4"] }
thiserror = "^1.0.20"

[dev-dependencies]
tokio = { version = "^1.22.0", features = ["full"] }
