[package]
name = "easymq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "^5.1.0"
futures-lite = "^1.11.0"
lapin = { version = "^2.2.0", optional = true }
serde = "^1.0.94"
postcard = { version = "^1.0.1", features = ["alloc"] }
tokio = { version = "^1.22.0", no-default-features = true, features = ["sync"] }
uuid = { version = "^1.3.2", features = ["v4"] }
thiserror = "^1.0.20"
async-trait = "0.1.73"
async-stream = "0.3.5"

[dev-dependencies]
tokio = { version = "^1.22.0", features = ["full"] }
postcard = { version = "^1.0.1", features = ["alloc"] }
serde_json = "^1.0.94"

[features]
default = ["lapin"]
lapin = ["dep:lapin"]
# json = ["dep:serde_json"]
# postcard = [""]
