[package]
name = "proto"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11"

[build-dependencies]
prost-build = { version = "0.11" }
