[package]
name = "easymq_derive"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.58"
syn = "2.0.22"
quote = "1.0.16"
darling = "0.20.0"
